// concept-j.jsx — Weekly Review. The reflection ritual.
// Hero: AI-generated week narrative. Stats: WoW comparison.
// Done celebration list. Features advanced. Plan next week.

function ConceptJ() {
  const { projects, todos, sessions } = window.AppData;
  const doneTodos = todos.filter(t => t.done);

  // Mock features advanced this week
  const featAdvanced = [
    { project: projects[0], name: 'OAuth flow', from: 40, to: 90 },
    { project: projects[0], name: 'Session store', from: 0, to: 60 },
    { project: projects[1], name: 'Layer model', from: 60, to: 88 },
    { project: projects[2], name: 'Slack handler', from: 80, to: 100, completed: true },
    { project: projects[2], name: 'Rate caps', from: 65, to: 100, completed: true },
    { project: projects[3], name: 'Lexer port', from: 30, to: 60 },
  ];

  return (
    <div className="dashboard-canvas">
      <div className="inner" style={{overflow:'hidden', height:'100%'}}>
        <Topbar />

        {/* Week header + nav */}
        <div className="wr-head">
          <div style={{display:'flex',alignItems:'center',gap:'1rem'}}>
            <button className="wr-nav">‹</button>
            <div>
              <div style={{fontFamily:'var(--font-mono)',fontSize:'0.7rem',color:'var(--text-muted)',textTransform:'uppercase',letterSpacing:'0.1em'}}>week 45 · review</div>
              <div style={{fontFamily:'var(--font-mono)',fontSize:'1.5rem',fontWeight:700,marginTop:2}}>
                <ShinyText>Nov 4 — Nov 10, 2025</ShinyText>
              </div>
            </div>
            <button className="wr-nav">›</button>
          </div>
          <div style={{display:'flex',gap:'0.5rem'}}>
            <button className="sd-action">📤 share with team</button>
            <button className="sd-action">📋 export markdown</button>
          </div>
        </div>

        {/* Row 1: AI summary + KPIs */}
        <div style={{display:'grid', gridTemplateColumns:'1.6fr 1fr', gap:'1.25rem', marginBottom:'1.25rem'}}>
          {/* AI narrative */}
          <div className="wr-summary">
            <ParticleField density={0.00007} color="191, 90, 242" maxLink={80} />
            <div className="wr-summary-inner">
              <div style={{display:'flex',alignItems:'center',gap:'0.5rem',marginBottom:'0.75rem'}}>
                <span style={{fontSize:'1.4rem',filter:'drop-shadow(0 0 12px var(--neon-purple))'}}>🧠</span>
                <span style={{fontFamily:'var(--font-mono)',fontSize:'0.78rem',color:'var(--neon-purple)',textTransform:'uppercase',letterSpacing:'0.1em',fontWeight:600}}>week summary</span>
                <span className="wr-summary-tag">auto-generated by haiku-4.5</span>
              </div>
              <div className="wr-narrative">
                <p>
                  <Typewriter
                    phrases={[
                      "Shipped haiku-bot v1.2 to prod — your biggest win this week. Slack handler + rate caps cleared 100%, 14/14 tests passing.",
                    ]}
                    speed={28}
                    pause={9999999}
                    cursor={false}
                  />
                </p>
                <p>
                  On <span className="wr-narr-pill cyan">🌌 aurora-api</span> you pushed the OAuth flow from 40% → 90%; the session store moved from nothing to a working draft. Two failing tests at end of week — picked up Monday.
                </p>
                <p>
                  <span className="wr-narr-pill purple">🎨 pixel-studio</span> made the layer model production-ready (88%). Hit-testing still 45% — blocked on canvas event delegation decision.
                </p>
                <p>
                  Burn was <strong>$28.40</strong> ↑ 18% vs last week, driven by the OAuth session storm (sonnet-4.5). Worth it.
                </p>
                <p style={{color:'var(--text-muted)',fontStyle:'italic'}}>
                  Suggested focus next week: pick up the 2 failing auth tests, then resume hit-testing.
                </p>
              </div>
            </div>
          </div>

          {/* KPIs with WoW */}
          <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'0.6rem',alignContent:'start'}}>
            <KpiTile label="todos done"     value={11} wow={+3}    color="var(--neon-green)"  />
            <KpiTile label="features +"     value={6}  wow={+2}    color="var(--neon-cyan)"   />
            <KpiTile label="sessions"       value={47} wow={+12}   color="var(--neon-purple)" />
            <KpiTile label="tokens · 7d"    value="1.24M" wow={+18} unit="%"  color="var(--neon-cyan)"  />
            <KpiTile label="cost · 7d"      value="$28.40" wow={+18} unit="%" color="var(--neon-orange)" warn />
            <KpiTile label="focus hours"    value="14.2h" wow={-1.4} unit="h" color="var(--neon-pink)" />
          </div>
        </div>

        {/* Row 2: done · features · WoW */}
        <div style={{display:'grid', gridTemplateColumns:'1fr 1fr 0.9fr', gap:'1.25rem', flex:1, minHeight:0}}>
          {/* Done this week */}
          <div className="surface" style={{display:'flex',flexDirection:'column',minHeight:0}}>
            <div className="sec-head" style={{marginBottom:'0.75rem'}}>
              <span className="prompt">&gt;</span> done this week
              <span className="count">— {doneTodos.length + 3} items</span>
              <span className="right" style={{color:'var(--neon-green)'}}>🎉</span>
            </div>
            <div style={{flex:1,overflowY:'auto',display:'flex',flexDirection:'column',gap:'0.6rem',paddingRight:4}}>
              <DoneGroup project={projects[0]} count={4} items={[
                'audit log schema — partition by tenant',
                'OAuth callback skeleton',
                'session store interface design',
                'rate-limit middleware first pass',
              ]} />
              <DoneGroup project={projects[1]} count={3} items={[
                'layer model: z-order persistence',
                'canvas pan/zoom inertia',
                'export: PNG @ 2x scale',
              ]} />
              <DoneGroup project={projects[2]} count={5} items={[
                'haiku-bot rate caps PR',
                'slack handler v1.2',
                'metrics dash skeleton',
                'smoke test pre-deploy',
                'changelog · v1.2',
              ]} />
              <DoneGroup project={projects[3]} count={2} items={[
                'lexer: handle escaped quotes in raw strings',
                'AST: visitor pattern scaffolding',
              ]} />
            </div>
          </div>

          {/* Features advanced */}
          <div className="surface" style={{display:'flex',flexDirection:'column',minHeight:0}}>
            <div className="sec-head" style={{marginBottom:'0.75rem'}}>
              <span className="prompt">&gt;</span> features advanced
              <span className="count">— {featAdvanced.length}</span>
            </div>
            <div style={{flex:1,overflowY:'auto',display:'flex',flexDirection:'column',gap:'0.85rem',paddingRight:4}}>
              {featAdvanced.map((f, i) => (
                <FeatureDelta key={i} f={f} />
              ))}
            </div>
          </div>

          {/* WoW comparison + top sessions */}
          <div style={{display:'flex',flexDirection:'column',gap:'1rem',minHeight:0,overflowY:'auto'}}>
            <div className="surface">
              <div className="sec-head" style={{marginBottom:'0.75rem'}}>
                <span className="prompt">&gt;</span> this week vs last
              </div>
              <WowCompare label="todos done" cur={11} prev={8} fmt={(n)=>n} />
              <WowCompare label="sessions"   cur={47} prev={35} fmt={(n)=>n} />
              <WowCompare label="tokens"     cur={1.24} prev={1.05} fmt={(n)=>n.toFixed(2)+'M'} />
              <WowCompare label="cost"       cur={28.4} prev={24.1} fmt={(n)=>'$'+n.toFixed(0)} warn />
              <WowCompare label="focus hrs"  cur={14.2} prev={15.6} fmt={(n)=>n.toFixed(1)+'h'} />
            </div>

            <div className="surface" style={{flex:1,minHeight:0,display:'flex',flexDirection:'column'}}>
              <div className="sec-head" style={{marginBottom:'0.75rem'}}>
                <span className="prompt">&gt;</span> top sessions
              </div>
              <div style={{display:'flex',flexDirection:'column',gap:'0.4rem',overflowY:'auto'}}>
                {sessions.filter(s => s.state !== 'error').slice(0, 3).map(s => <SessionRow key={s.id} s={s} compact />)}
              </div>
            </div>
          </div>
        </div>

        {/* Next week plan */}
        <div style={{marginTop:'1.25rem'}}>
          <div className="sec-head" style={{marginBottom:'0.75rem'}}>
            <span className="prompt">&gt;</span> plan next week
            <span className="count">— drop todos here · auto-budget estimate</span>
            <span className="right" style={{fontFamily:'var(--font-mono)',fontSize:'0.78rem'}}>
              budgeted: <span style={{color:'var(--neon-cyan)'}}>~$32</span> · <span style={{color:'var(--neon-purple)'}}>~22 sessions</span>
            </span>
          </div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(5, 1fr)',gap:'0.75rem'}}>
            {['mon','tue','wed','thu','fri'].map((d, di) => (
              <NextWeekDay key={d} day={d}
                pinned={di === 0 ? [
                  { p: projects[0].emoji, name: 'fix 2 failing auth tests', proj: projects[0].name },
                  { p: projects[2].emoji, name: 'metrics dash polish', proj: projects[2].name },
                ] : di === 1 ? [
                  { p: projects[1].emoji, name: 'resume hit-testing', proj: projects[1].name },
                ] : di === 2 ? [
                  { p: projects[0].emoji, name: 'audit log impl', proj: projects[0].name },
                  { p: '💡', name: 'reply to sam contract', proj: 'inbox' },
                ] : di === 3 ? [
                  { p: projects[3].emoji, name: 'port lexer fixtures', proj: projects[3].name },
                ] : []}
              />
            ))}
          </div>
        </div>
      </div>
      <style>{conceptJStyles}</style>
    </div>
  );
}

function KpiTile({ label, value, wow, unit, color, warn }) {
  const up = (typeof wow === 'number') && wow > 0;
  const wowStr = wow == null ? '' : `${up ? '↑' : '↓'} ${Math.abs(wow)}${unit || ''}`;
  return (
    <div className="wr-kpi">
      <div className="wr-kpi-label">{label}</div>
      <div className="wr-kpi-value" style={{color}}>
        {typeof value === 'number'
          ? <CountUp to={value} duration={1000} />
          : value}
      </div>
      {wow != null && (
        <div className="wr-kpi-wow" style={{color: warn ? 'var(--neon-orange)' : up ? 'var(--neon-green)' : 'var(--neon-pink)'}}>
          {wowStr} <span style={{color:'var(--text-muted)'}}>vs prev</span>
        </div>
      )}
    </div>
  );
}

function DoneGroup({ project, count, items }) {
  return (
    <div className="wr-done-group">
      <div className="wr-done-head">
        <span style={{fontSize:'1.05rem'}}>{project.emoji}</span>
        <span style={{fontFamily:'var(--font-mono)',fontSize:'0.82rem',color:'var(--neon-cyan)',fontWeight:600}}>{project.name}</span>
        <span style={{fontFamily:'var(--font-mono)',fontSize:'0.7rem',color:'var(--neon-green)',marginLeft:'auto',background:'rgba(48,209,88,0.1)',padding:'1px 7px',borderRadius:'var(--radius-pill)'}}>✓ {count}</span>
      </div>
      <div style={{display:'flex',flexDirection:'column',gap:3,marginTop:6}}>
        {items.map((t, i) => (
          <div key={i} className="wr-done-item">
            <span className="wr-done-check">✓</span>
            <span className="wr-done-text">{t}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function FeatureDelta({ f }) {
  const delta = f.to - f.from;
  return (
    <div className="wr-feat">
      <div style={{display:'flex',alignItems:'center',gap:6,marginBottom:6}}>
        <span style={{fontSize:'1rem'}}>{f.project.emoji}</span>
        <span style={{fontFamily:'var(--font-mono)',fontSize:'0.7rem',color:'var(--text-muted)'}}>{f.project.name}</span>
        <span style={{flex:1}}/>
        {f.completed && <span style={{fontFamily:'var(--font-mono)',fontSize:'0.66rem',color:'var(--neon-green)',background:'rgba(48,209,88,0.1)',padding:'1px 6px',borderRadius:'var(--radius-sm)',fontWeight:600}}>SHIPPED</span>}
      </div>
      <div style={{fontFamily:'var(--font-mono)',fontSize:'0.85rem',color:'var(--text-primary)',fontWeight:500,marginBottom:6}}>{f.name}</div>
      <div style={{position:'relative',height:8,background:'var(--bg-elevated)',borderRadius:4,overflow:'hidden'}}>
        {/* from state in muted */}
        <div style={{position:'absolute',inset:0,width:f.from+'%',background:'rgba(160,160,176,0.25)'}}/>
        {/* to state in cyan */}
        <div style={{position:'absolute',inset:0,width:f.to+'%',background: f.completed ? 'var(--gradient-success)' : 'var(--gradient-primary)',boxShadow:`0 0 8px ${f.completed?'var(--neon-green)':'var(--neon-cyan)'}`,transition:'width 0.8s var(--ease-smooth)'}}/>
        {/* delta marker */}
        <div style={{position:'absolute',top:-2,left:f.from+'%',width:1,height:12,background:'var(--text-muted)'}}/>
      </div>
      <div style={{display:'flex',justifyContent:'space-between',marginTop:5,fontFamily:'var(--font-mono)',fontSize:'0.7rem'}}>
        <span style={{color:'var(--text-muted)'}}>{f.from}%</span>
        <span style={{color:'var(--neon-green)',fontWeight:600}}>+{delta}%</span>
        <span style={{color: f.completed ? 'var(--neon-green)' : 'var(--neon-cyan)',fontWeight:600}}>{f.to}%</span>
      </div>
    </div>
  );
}

function WowCompare({ label, cur, prev, fmt, warn }) {
  const delta = ((cur - prev) / prev) * 100;
  const up = delta > 0;
  return (
    <div className="wr-wow-row">
      <div style={{fontFamily:'var(--font-mono)',fontSize:'0.7rem',color:'var(--text-muted)',marginBottom:3,display:'flex',justifyContent:'space-between'}}>
        <span>{label}</span>
        <span style={{color: warn ? 'var(--neon-orange)' : up ? 'var(--neon-green)' : 'var(--neon-pink)',fontWeight:600}}>
          {up ? '↑' : '↓'} {Math.abs(delta).toFixed(0)}%
        </span>
      </div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6,alignItems:'center'}}>
        <div style={{display:'flex',alignItems:'center',gap:6}}>
          <span style={{fontFamily:'var(--font-mono)',fontSize:'0.62rem',color:'var(--text-muted)',width:22}}>prev</span>
          <div className="pbar thin" style={{flex:1}}>
            <div className="pbar-fill" style={{width:'100%',background:'var(--text-muted)',opacity:0.4,boxShadow:'none',animation:'none'}}/>
          </div>
        </div>
        <div style={{display:'flex',alignItems:'center',gap:6}}>
          <span style={{fontFamily:'var(--font-mono)',fontSize:'0.62rem',color:'var(--text-secondary)',width:22}}>now</span>
          <div className="pbar thin" style={{flex:1}}>
            <div className="pbar-fill" style={{width: Math.min(100, (cur / prev) * 100)+'%',background: warn ? 'var(--neon-orange)' : 'var(--gradient-primary)'}}/>
          </div>
        </div>
      </div>
      <div style={{display:'flex',justifyContent:'space-between',marginTop:3,fontFamily:'var(--font-mono)',fontSize:'0.7rem'}}>
        <span style={{color:'var(--text-muted)'}}>{fmt(prev)}</span>
        <span style={{color:'var(--text-primary)',fontWeight:600}}>{fmt(cur)}</span>
      </div>
    </div>
  );
}

function NextWeekDay({ day, pinned }) {
  return (
    <div className="wr-nwd">
      <div className="wr-nwd-head">{day}</div>
      <div style={{display:'flex',flexDirection:'column',gap:4,flex:1}}>
        {pinned.map((p, i) => (
          <div key={i} className="wr-nwd-todo">
            <span style={{fontSize:'0.85rem'}}>{p.p}</span>
            <div style={{flex:1,minWidth:0}}>
              <div style={{fontFamily:'var(--font-mono)',fontSize:'0.74rem',color:'var(--text-primary)',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{p.name}</div>
              <div style={{fontFamily:'var(--font-mono)',fontSize:'0.62rem',color: p.proj === 'inbox' ? 'var(--neon-orange)' : 'var(--neon-cyan)',marginTop:1}}>#{p.proj}</div>
            </div>
          </div>
        ))}
        <button className="wr-nwd-add">+ drop here</button>
      </div>
    </div>
  );
}

const conceptJStyles = `
.wr-head {
  display: flex; justify-content: space-between; align-items: center;
  margin-bottom: 1.25rem;
  padding: 0.75rem 1rem;
  background: var(--bg-glass);
  border: 1px solid var(--border-subtle);
  border-radius: var(--radius-lg);
}
.wr-nav {
  width: 32px; height: 32px;
  background: var(--bg-elevated);
  border: 1px solid var(--border-subtle);
  color: var(--text-secondary);
  border-radius: 8px;
  cursor: pointer;
  font-size: 1.1rem;
  font-family: var(--font-mono);
}
.wr-nav:hover { border-color: var(--neon-cyan); color: var(--neon-cyan); }

.wr-summary {
  position: relative;
  background: linear-gradient(135deg, rgba(191,90,242,0.08), rgba(0,255,242,0.04));
  border: 1px solid rgba(191,90,242,0.25);
  border-radius: var(--radius-lg);
  padding: 1.25rem 1.5rem;
  overflow: hidden;
  box-shadow: inset 0 1px 0 rgba(255,255,255,0.06), 0 0 30px rgba(191,90,242,0.05);
}
.wr-summary-inner { position: relative; z-index: 1; }
.wr-summary-tag {
  font-family: var(--font-mono);
  font-size: 0.62rem;
  color: var(--text-muted);
  background: var(--bg-elevated);
  border: 1px solid var(--border-hair);
  padding: 1px 7px;
  border-radius: var(--radius-pill);
  margin-left: auto;
}
.wr-narrative {
  font-family: var(--font-body);
  font-size: 0.92rem;
  line-height: 1.65;
  color: var(--text-primary);
}
.wr-narrative p { margin: 0; margin-bottom: 0.55rem; }
.wr-narrative p:last-child { margin-bottom: 0; }
.wr-narrative strong { color: var(--neon-orange); font-weight: 600; }
.wr-narr-pill {
  display: inline-flex; align-items: center;
  font-family: var(--font-mono);
  font-size: 0.8rem;
  padding: 1px 8px;
  border-radius: var(--radius-sm);
  font-weight: 500;
}
.wr-narr-pill.cyan   { background: rgba(0,255,242,0.08); color: var(--neon-cyan); border: 1px solid rgba(0,255,242,0.2); }
.wr-narr-pill.purple { background: rgba(191,90,242,0.08); color: var(--neon-purple); border: 1px solid rgba(191,90,242,0.2); }

.wr-kpi {
  background: var(--bg-glass);
  backdrop-filter: blur(20px);
  border: 1px solid var(--border-subtle);
  border-radius: var(--radius-md);
  padding: 0.7rem 0.85rem;
  position: relative;
  overflow: hidden;
}
.wr-kpi::before {
  content: ''; position: absolute; top: 0; left: 0; right: 0; height: 2px;
  background: var(--gradient-primary);
}
.wr-kpi-label {
  font-family: var(--font-mono);
  font-size: 0.62rem;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.06em;
}
.wr-kpi-value {
  font-family: var(--font-mono);
  font-size: 1.45rem;
  font-weight: 700;
  margin-top: 2px;
  font-variant-numeric: tabular-nums;
  line-height: 1.1;
}
.wr-kpi-wow {
  font-family: var(--font-mono);
  font-size: 0.66rem;
  margin-top: 3px;
}

.wr-done-group {
  padding: 0.7rem 0.85rem;
  background: rgba(48,209,88,0.03);
  border: 1px solid rgba(48,209,88,0.15);
  border-radius: var(--radius-md);
}
.wr-done-head { display: flex; align-items: center; gap: 0.5rem; }
.wr-done-item {
  display: flex; align-items: flex-start; gap: 0.5rem;
  font-family: var(--font-mono);
  font-size: 0.76rem;
  color: var(--text-secondary);
  padding: 2px 0;
}
.wr-done-check {
  color: var(--neon-green);
  font-weight: 700;
  text-shadow: 0 0 8px rgba(48,209,88,0.6);
  flex-shrink: 0;
}
.wr-done-text { line-height: 1.5; }

.wr-feat {
  padding: 0.75rem 0.85rem;
  background: var(--bg-glass);
  border: 1px solid var(--border-hair);
  border-radius: var(--radius-md);
}

.wr-wow-row { padding: 0.55rem 0; border-bottom: 1px solid var(--border-hair); }
.wr-wow-row:last-child { border-bottom: 0; }

.wr-nwd {
  background: var(--bg-glass);
  border: 1px solid var(--border-hair);
  border-radius: var(--radius-md);
  padding: 0.6rem 0.7rem;
  display: flex; flex-direction: column; gap: 0.5rem;
  min-height: 130px;
}
.wr-nwd-head {
  font-family: var(--font-mono);
  font-size: 0.72rem;
  font-weight: 700;
  color: var(--neon-cyan);
  text-transform: uppercase;
  letter-spacing: 0.1em;
  padding-bottom: 0.35rem;
  border-bottom: 1px solid var(--border-hair);
}
.wr-nwd-todo {
  display: flex; gap: 6px; align-items: flex-start;
  padding: 5px 6px;
  background: rgba(255,255,255,0.025);
  border: 1px solid var(--border-hair);
  border-radius: var(--radius-sm);
  cursor: grab;
}
.wr-nwd-todo:hover { border-color: var(--border-glow); }
.wr-nwd-add {
  background: transparent;
  border: 1px dashed var(--border-subtle);
  color: var(--text-muted);
  padding: 6px;
  border-radius: var(--radius-sm);
  font-family: var(--font-mono);
  font-size: 0.7rem;
  cursor: pointer;
  margin-top: auto;
}
.wr-nwd-add:hover { border-color: var(--neon-cyan); color: var(--neon-cyan); }
`;

window.ConceptJ = ConceptJ;
